
services:
  #Service PHP
  php:
    build:
      context: .  #Répertoire racine
      dockerfile: docker/php/Dockerfile #Chemin vers le dockerfil
    working_dir: /var/www/symfony
    volumes: #Montage du code source
      - .:/var/www/symfony
    depends_on: #Dépend du service database
      - database
      - mongodb
    networks: #Resaux paratgé
      - symfony
    environment:
      PHP_MEMORY_LIMIT: "256M"
    image: php:fpm
    ports:
      - "9000:9000"
    command: >
      bash -c "
        chown -R www-data:www-data /var/www/symfony/var &&
        chmod -R 775 /var/www/symfony/var &&
        php-fpm
      "

  # Service Composer séparé
  composer:
    image: composer:latest
    volumes:
      - .:/app
    working_dir: /app
    networks:
      - symfony

  #Serveur Web Nginx
  nginx:
    image: nginx:alpine
    ports:
      - "8080:80"  #Port(conteneur local)
    volumes:
      - .:/var/www/symfony  #Montage CS
      - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf  #config Nginx
    depends_on:
      - php
    networks:
      - symfony

  #Service base de donnée MYSQL
  database:
    image: mysql:8.0
    environment: #Varable env MySQL
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: ecoride
      MYSQL_USER: symfony
      MYSQL_PASSWORD: symfony
    ports:
      - "3306:3306"
    volumes:
      - db-data:/var/lib/mysql
      - ./config/sql:/docker-entrypoint-initdb.d
    networks:
      - symfony
    command: --default-authentication-plugin=mysql_native_password
    restart: always

    ##Use phpADMIN
  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    ports:
        - "8081:80"
    environment:
        PMA_HOST: database
        MYSQL_ROOT_PASSWORD: root
        PMA_USER: root
        PMA_PASSWORD: root
    depends_on:
        - database
    networks:
        - symfony
  
  #Service mongoDB
  mongodb:
    image: mongo:6.0
    container_name: ecoride_mongodb
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: admin123
      MONGO_INITDB_DATABASE: ecoride_analytics
    ports:
      - "27017:27017"
    volumes:
      - mongodb_data:/data/db
    networks:
      - symfony

  # Interface MongoDB (Mongo Express)
  mongo-express:
    image: mongo-express:latest
    container_name: ecoride_mongo_express
    restart: always
    ports:
      - "8082:8081"  # Changé le port pour éviter le conflit avec phpMyAdmin
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: admin
      ME_CONFIG_MONGODB_ADMINPASSWORD: admin123
      ME_CONFIG_MONGODB_URL: mongodb://admin:admin123@mongodb:27017/
      ME_CONFIG_BASICAUTH_USERNAME: admin
      ME_CONFIG_BASICAUTH_PASSWORD: admin123
    depends_on:
      - mongodb
    networks:
      - symfony

#Définision des réseaux
networks:
  symfony:  #réseau isolé pour les conteneurs

#Définition des volumes persistants
volumes:
  db-data:  #volume pour les données MySQL
  mongodb_data: #volume pour les données NoSQL
###> doctrine/doctrine-bundle ###
  database_data:
###< doctrine/doctrine-bundle ###
