version: '3'

services:
  php:
    build:
      context: .
      dockerfile: docker/php/Dockerfile
      args:
        - APP_ENV=prod
    volumes:
      - ./:/var/www/symfony:cached
    depends_on:
      - database
    networks:
      - symfony
    restart: unless-stopped
    ports:
      - "9000:9000"
    environment:
      APP_ENV: prod

  nginx:
    image: nginx:alpine
    ports:
      - "80:80"
      - "443:443" # Pour HTTPS
    volumes:
      - ./:/var/www/symfony:cached
      - ./docker/nginx/default.prod.conf:/etc/nginx/conf.d/default.conf:ro
      - ./ssl:/etc/nginx/ssl:ro # Pour les certificats SSL
    depends_on:
      - php
    networks:
      - symfony
    restart: unless-stopped

  database:
    image: mysql:8.0
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
    volumes:
      - db-data:/var/lib/mysql
    networks:
      - symfony
    restart: unless-stopped

networks:
  symfony:

volumes:
  db-data: